GET http://localhost:3000/subscribers
// returns an array of objects containing the correct data sets

###

GET http://localhost:3000/subscribers/5e48fd6ffc81d80ed86241c3

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Testing",
  "subscribedChannel": "Test Channel"
}
// works as intended

###

DELETE http://localhost:3000/subscribers/5e49eebfce6ad66208796a05

###

PATCH http://localhost:3000/subscribers/5e49ebc12446a635b873bc7b
Content-Type: application/json 

{
  "name": "Pancake"
}