GET http://localhost:3000/subscribers
// returns an array of objects containing the correct data sets

###

GET http://localhost:3000/subscribers/5e4a4223972852541c71cb09
// works as intended finally after commenting out 'use strict'

###

POST http://localhost:3000/subscribers
Content-Type: application/json
// space here is necessary in order for this to work https://github.com/Huachao/vscode-restclient/issues/430#issuecomment-538784585
{
  "name": "Pancake",
  "subscribedChannel": "Pancakes Channel"
}
// works as intended

###

DELETE http://localhost:3000/subscribers/5e49ebc12446a635b873bc7b
// works as intended

###

PATCH http://localhost:3000/subscribers/5e4a513cdee8a32808187af5
Content-Type: application/json 

{
  "name": "Pizza",
  "subscribedChannel": "Pizza Channel"
}
// works as intended